import turtle
finishline = turtle.Pen()
finishline.up()
finishline.forward(200)
finishline.right(90)
finishline.forward(200)
finishline.width(10)
finishline.pencolor('#000000')
finishline.down()
finishline.backward(400)
finishline.up()
finishline.left(90)
finishline.forward(20)
finishline.right(90)
finishline.down()
finishline.forward(400)
finishline.up()
finishline.left(90)
finishline.forward(20)
finishline.left(90)
finishline.down()
finishline.forward(400)
