import pyinputplus as pyip
print('All pyip inputNum tests')
response = pyip.inputNum(prompt='Enter a number')
print(response)
ans = pyip.inputNum(propmt='Enter a num(Blank Allowed)', blank=True)
print(ans)
minmaxInput = pyip.inputNum(prompt='Enter num(min 79, max109)', min=79, max=109)
print(minmaxInput)
limitInput = pyip.inputNum(prompt='Enter num(5 wrongs allowed, default is N/A)', limit=5, default='N/A')
print(limitInput)
timeoutInput = pyip.inputNum(prompt='Enter num(No longer than 10 seconds, default is N/A)', timeout=10, default='N/A')
print(timeoutInput)
romanInput = pyip.inputNum(prompt='Enter Roman numeral', allowRegexes=[r'(I|V|X|L|C|D|M)+', r'zero'])
print(romanInput)
oddInput = pyip.inputNum(prompt='Enter odd num', blockRegexes=[r'[02468]$'])
print(oddInput)
evenInput = pyip.inputNum(prompt='Enter even num', blockRegexes=[r'[13579]$'])
